### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by PaulRegular** [PaulRegular/SimSurvey#1]
- [x] Add function for simulating a stratified random survey (sim_sets)
- [x] Add function for simulating complete catch (sim_catch; include growth function here to generate lengths) 
- [x] Add sampling functions (set catch, lengths measured, otoliths aged) (sim_samp)
- [x] Add stratified analysis function to obtain strat estimates from simulated survey data
- [x] Add function for testing different survey sampling scenarios
- [x] Use foreach (parallel loop) to speed up test_surveys function
- [x] Profile code to look for efficiencies
- [x] Make a surveys function and modify test_surveys to take the object as an input (vs test_surveys building the grid of surveys internally)
- [x] Enable saving of RData or csv in test_surveys function and add a resume argument
- [x] Add plots of survey sampling to vis_sim flexdashboard
- [x] Calculate intra-haul correlation on real and simulated data (i.e. ICC)
- [x] For the test_survey function, consider using data.table::fwrite and save each survey result in a .csv versus current base::save strategy
- [x] Retain sample size info in survey statistics tables
- [x] Replace current estimate plot with fancharts in vis_sim flexdashboard
- [ ] Colour code sets where length cap was reached
- [ ] Try and figure out a visual for showing if age cap was reached
- [ ] Test survey scenarios on a 'cod' population with decreased patchiness and / or a population tailored to other species
- [ ] Write a description of the age-year-space covariance process used in the sim_distribution function
- [ ] Add function for calculating effective sample size
- [ ] Consider alternates to the RMSE metric that better represents fits to the tails of the population (e.g. log-based metric suggested by Geoff)
